// <auto-generated />
using System;
using CHL.NrbGateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CHL.NrbGateway.Infrastructure.Migrations
{
    [DbContext(typeof(KycDbContext))]
    [Migration("20260810123439_InitialKyc")]
    partial class InitialKyc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kyc")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.GatewayRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NrbVerificationEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServedFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubsidiaryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("NrbVerificationEventId");

                    b.ToTable("gateway_requests", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.Individual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CivilStatus")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FingerprintRef")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaidenName")
                        .HasColumnType("text");

                    b.Property<string>("NationalIdEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("NationalIdHash")
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("OtherNames")
                        .HasColumnType("text");

                    b.Property<string>("PhotoRef")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirthDistrict")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirthVillage")
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NationalIdHash")
                        .IsUnique();

                    b.ToTable("individuals", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityTownCountry")
                        .HasColumnType("text");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<string>("Line1Line2")
                        .HasColumnType("text");

                    b.Property<string>("StreetNameVillage")
                        .HasColumnType("text");

                    b.Property<string>("TraditionalAuthorityDistrict")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("individual_addresses", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualContactDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsNrbRegisteredPhone")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("individual_contact_details", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualEmployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("individual_employment", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualFieldVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Superseded")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("individual_field_verification", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualIdentification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateOfExpiry")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfIssue")
                        .HasColumnType("date");

                    b.Property<string>("IdStatus")
                        .HasColumnType("text");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("individual_identifications", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualNextOfKin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstNameLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumberEmail")
                        .HasColumnType("text");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("individual_next_of_kin", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("text");

                    b.Property<Guid?>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<string>("PinSubmittedHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawResponseRef")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestingSubsidiary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ResponseTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("PinSubmittedHash");

                    b.ToTable("nrb_verification_events", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryOfIncorporation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateEstablished")
                        .HasColumnType("date");

                    b.Property<bool>("EverInsolvent")
                        .HasColumnType("boolean");

                    b.Property<string>("FinancialYearEnd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForeignCountry")
                        .HasColumnType("text");

                    b.Property<string>("HoldingCompanyName")
                        .HasColumnType("text");

                    b.Property<string>("IncomeTaxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("InsolvencyRehabilitatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsSubsidiary")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MonthlyTurnover")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NatureOfBusiness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("integer");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("organizations", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1Line2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailWebsite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelNumberFaxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("organization_addresses", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttachmentType")
                        .HasColumnType("integer");

                    b.Property<string>("FileRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("organization_attachments", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelNumberFaxNumberCellNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("organization_contacts", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationExistingScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmployerNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchemeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("organization_existing_schemes", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationSignatory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AuthorizedFrom")
                        .HasColumnType("date");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SignatureRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("organization_signatories", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.GatewayRequest", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany()
                        .HasForeignKey("IndividualId");

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", "NrbVerificationEvent")
                        .WithMany("GatewayRequests")
                        .HasForeignKey("NrbVerificationEventId");

                    b.Navigation("Individual");

                    b.Navigation("NrbVerificationEvent");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualAddress", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("Addresses")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualContactDetail", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("ContactDetails")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualEmployment", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("Employments")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Individual");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualFieldVerification", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("FieldVerifications")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualIdentification", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("Identifications")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualNextOfKin", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("NextOfKins")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("VerificationEvents")
                        .HasForeignKey("IndividualId");

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationAddress", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Organization", "Organization")
                        .WithMany("Addresses")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationAttachment", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Organization", "Organization")
                        .WithMany("Attachments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationContact", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Organization", "Organization")
                        .WithMany("Contacts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationExistingScheme", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Organization", "Organization")
                        .WithMany("ExistingSchemes")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.OrganizationSignatory", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany()
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Organization", "Organization")
                        .WithMany("Signatories")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.Individual", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactDetails");

                    b.Navigation("Employments");

                    b.Navigation("FieldVerifications");

                    b.Navigation("Identifications");

                    b.Navigation("NextOfKins");

                    b.Navigation("VerificationEvents");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", b =>
                {
                    b.Navigation("GatewayRequests");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.Organization", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Attachments");

                    b.Navigation("Contacts");

                    b.Navigation("ExistingSchemes");

                    b.Navigation("Signatories");
                });
#pragma warning restore 612, 618
        }
    }
}
