// <auto-generated />
using System;
using CHL.NrbGateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CHL.NrbGateway.Infrastructure.Migrations
{
    [DbContext(typeof(KycDbContext))]
    [Migration("20260817212615_InitialKyc")]
    partial class InitialKyc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kyc")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.GatewayRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostIncurred")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("NrbVerificationEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServedFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NrbVerificationEventId");

                    b.HasIndex("SubjectId");

                    b.ToTable("gateway_requests", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IdentityLookup", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NationalIdEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalIdHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubjectId");

                    b.HasIndex("NationalIdHash")
                        .IsUnique();

                    b.ToTable("identity_lookup", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.Individual", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("BirthDistrict")
                        .HasColumnType("text");

                    b.Property<string>("CardStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CivilStatus")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("IdDateOfExpiry")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IdDateOfIssue")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastCardCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastMiddlewareCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiddlewareStatus")
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("NrbRegisteredPhone")
                        .HasColumnType("text");

                    b.Property<string>("OtherNames")
                        .HasColumnType("text");

                    b.Property<string>("ResidenceAddress")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubjectId");

                    b.ToTable("individuals", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobFormat")
                        .HasColumnType("text");

                    b.Property<string>("BlobRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FingerPosition")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("individual_documents", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualSourceValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("individual_source_values", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbFieldCheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("nrb_field_check_results", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("text");

                    b.Property<string>("PinSubmittedEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("PinSubmittedHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawResponseRef")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestingProjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ResponseTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevalidationBatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PinSubmittedHash");

                    b.HasIndex("SubjectId");

                    b.ToTable("nrb_verification_events", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.GatewayRequest", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", "NrbVerificationEvent")
                        .WithMany("GatewayRequests")
                        .HasForeignKey("NrbVerificationEventId");

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.IdentityLookup", "Subject")
                        .WithMany("GatewayRequests")
                        .HasForeignKey("SubjectId");

                    b.Navigation("NrbVerificationEvent");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.Individual", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.IdentityLookup", "IdentityLookup")
                        .WithOne("Individual")
                        .HasForeignKey("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityLookup");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualDocument", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("Documents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualSourceValue", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("SourceValues")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbFieldCheckResult", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.IdentityLookup", "Subject")
                        .WithMany("FieldCheckResults")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.IdentityLookup", "Subject")
                        .WithMany("VerificationEvents")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IdentityLookup", b =>
                {
                    b.Navigation("FieldCheckResults");

                    b.Navigation("GatewayRequests");

                    b.Navigation("Individual");

                    b.Navigation("VerificationEvents");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.Individual", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SourceValues");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", b =>
                {
                    b.Navigation("GatewayRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
