// <auto-generated />
using System;
using CHL.NrbGateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CHL.NrbGateway.Infrastructure.Migrations
{
    [DbContext(typeof(KycDbContext))]
    partial class KycDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kyc")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.GatewayRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NrbVerificationEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServedFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubsidiaryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("NrbVerificationEventId");

                    b.ToTable("gateway_requests", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.Individual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BirthDistrict")
                        .HasColumnType("text");

                    b.Property<string>("CardStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FingerPosition")
                        .HasColumnType("text");

                    b.Property<string>("FingerprintRef")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastRevalidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text");

                    b.Property<string>("NationalIdEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("NationalIdHash")
                        .HasColumnType("text");

                    b.Property<string>("OtherNames")
                        .HasColumnType("text");

                    b.Property<string>("PhotoRef")
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResidentialAddress")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NationalIdHash")
                        .IsUnique();

                    b.ToTable("individuals", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualFieldVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Superseded")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("individual_field_verification", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualIdentification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateOfExpiry")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfIssue")
                        .HasColumnType("date");

                    b.Property<string>("IdStatus")
                        .HasColumnType("text");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("individual_identifications", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("text");

                    b.Property<Guid?>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<string>("PinSubmittedHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawResponseRef")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestingSubsidiary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ResponseTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("PinSubmittedHash");

                    b.ToTable("nrb_verification_events", "kyc");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.GatewayRequest", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany()
                        .HasForeignKey("IndividualId");

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", "NrbVerificationEvent")
                        .WithMany("GatewayRequests")
                        .HasForeignKey("NrbVerificationEventId");

                    b.Navigation("Individual");

                    b.Navigation("NrbVerificationEvent");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualFieldVerification", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("FieldVerifications")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.IndividualIdentification", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("Identifications")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Kyc.Individual", "Individual")
                        .WithMany("VerificationEvents")
                        .HasForeignKey("IndividualId");

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.Individual", b =>
                {
                    b.Navigation("FieldVerifications");

                    b.Navigation("Identifications");

                    b.Navigation("VerificationEvents");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Kyc.NrbVerificationEvent", b =>
                {
                    b.Navigation("GatewayRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
