services:
  postgres:
    image: postgres:18-alpine
    container_name: chl_nrb_gateway_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: chl_nrb_gateway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql
      - ./scripts/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chl_nrb_gateway"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
