// <auto-generated />
using System;
using CHL.NrbGateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CHL.NrbGateway.Infrastructure.Migrations.ConfigDb
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20260810123459_InitialConfig")]
    partial class InitialConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("config")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admin_users", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.CacheRetentionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreshnessUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FreshnessValue")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("cache_retention_policy", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.ConfigAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid?>("RollbackOfId")
                        .HasColumnType("uuid");

                    b.Property<string>("SettingArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("RollbackOfId");

                    b.ToTable("config_audit_log", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.NrbEnvironmentSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvancedEndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BasicEndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntermediateEndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextLookupEndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("nrb_environment_settings", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.Subsidiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("subsidiaries", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.SubsidiaryApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RotatedAtRevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubsidiaryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("SubsidiaryId");

                    b.ToTable("subsidiary_api_keys", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.VerificationTierSetting", b =>
                {
                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Tier");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("verification_tier_settings", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.CacheRetentionPolicy", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "UpdatedByAdmin")
                        .WithMany("UpdatedCachePolicies")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.ConfigAuditLog", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "AdminUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.ConfigAuditLog", "RollbackOfEntry")
                        .WithMany()
                        .HasForeignKey("RollbackOfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdminUser");

                    b.Navigation("RollbackOfEntry");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.NrbEnvironmentSetting", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "UpdatedByAdmin")
                        .WithMany("UpdatedEnvSettings")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.SubsidiaryApiKey", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "CreatedByAdmin")
                        .WithMany("CreatedApiKeys")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.Subsidiary", "Subsidiary")
                        .WithMany("ApiKeys")
                        .HasForeignKey("SubsidiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Subsidiary");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.VerificationTierSetting", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "UpdatedByAdmin")
                        .WithMany("UpdatedTierSettings")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.AdminUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedApiKeys");

                    b.Navigation("UpdatedCachePolicies");

                    b.Navigation("UpdatedEnvSettings");

                    b.Navigation("UpdatedTierSettings");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.Subsidiary", b =>
                {
                    b.Navigation("ApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
