// <auto-generated />
using System;
using CHL.NrbGateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CHL.NrbGateway.Infrastructure.Migrations.ConfigDb
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20260819101047_AddAdminOtpCodes")]
    partial class AddAdminOtpCodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("config")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.AdminOtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("admin_otp_codes", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admin_users", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.BillingInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GeneratedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("billing_invoices", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("companies", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.ConfigAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid?>("RollbackOfId")
                        .HasColumnType("uuid");

                    b.Property<string>("SettingArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("RollbackOfId");

                    b.ToTable("config_audit_log", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.MonthlyUsageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "PeriodYear", "PeriodMonth")
                        .IsUnique();

                    b.ToTable("monthly_usage_reports", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("notification_channels", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.NrbDowntimeIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DetectedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Notified")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedBy");

                    b.ToTable("nrb_downtime_incidents", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.NrbEnvironmentSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvancedEndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BasicEndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntermediateEndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextLookupEndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("nrb_environment_settings", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.NrbHealthCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsUp")
                        .HasColumnType("boolean");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("nrb_health_checks", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("projects", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.ProjectApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RotatedAtRevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("project_api_keys", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.RevalidationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InitiatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedBy");

                    b.ToTable("revalidation_batches", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.VerificationTierSetting", b =>
                {
                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<decimal>("CostPerRequest")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Tier");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("verification_tier_settings", "config");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.AdminOtpCode", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "Admin")
                        .WithMany("OtpCodes")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.BillingInvoice", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "GeneratedByAdmin")
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("GeneratedByAdmin");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.ConfigAuditLog", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "AdminUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.ConfigAuditLog", "RollbackOfEntry")
                        .WithMany()
                        .HasForeignKey("RollbackOfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdminUser");

                    b.Navigation("RollbackOfEntry");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.NotificationChannel", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "CreatedByAdmin")
                        .WithMany("CreatedNotificationChannels")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.NrbDowntimeIncident", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "ResolvedByAdmin")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResolvedByAdmin");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.NrbEnvironmentSetting", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "UpdatedByAdmin")
                        .WithMany("UpdatedEnvSettings")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.Project", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.ProjectApiKey", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "CreatedByAdmin")
                        .WithMany("CreatedApiKeys")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.Project", "Project")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.RevalidationBatch", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Initiator");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.VerificationTierSetting", b =>
                {
                    b.HasOne("CHL.NrbGateway.Domain.Entities.Config.AdminUser", "UpdatedByAdmin")
                        .WithMany("UpdatedTierSettings")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.AdminUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedApiKeys");

                    b.Navigation("CreatedNotificationChannels");

                    b.Navigation("OtpCodes");

                    b.Navigation("UpdatedEnvSettings");

                    b.Navigation("UpdatedTierSettings");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CHL.NrbGateway.Domain.Entities.Config.Project", b =>
                {
                    b.Navigation("ApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
